#!/bin/bash

sudo apt update
sudo apt upgrade
sudo apt-get install git \
  build-essential bc kmod cpio flex libncurses5-dev libelf-dev libssl-dev dwarves bison \
  cdebootstrap
echo "If you think you might need a reboot based on what what installed then press ctl-c and sudo reboot"
echo "else press return"
read
cd ~
#git clone https://github.com/SESA/appbuilder.git
if ! git clone git@github.com:jappavoo/nbic.git; then
  cat <<EOF
Please note the nbic repo is private and you will need jappavoo to give you access.  Eg.
$ ssh-keygen
$ cat ~/.ssh/id_rsa.pub 
Send to jappavoo@bu.edu and say, "Pretty please, give me access to nbic -- Oh master and ruler of the known universe."
Then you should be able to `git clone https://github.com/jappavoo/nbic.git`
EOF
fi


