#!/bin/bash
#set -x
scriptdir=$(dirname $(realpath $0))
disk=$1
disk=${disk:-$APPBUILDERVM}
APPBUILDER_SSHLOCAL=${APPBUILDER_SSHLOCAL:-"127.0.0.1:2222"}

if [[ -z $disk ]]; then
    if [[ -n $APPBUILDERVM  ]]; then
	echo "ERROR: missing $APPBUILDERVM"
	echo "USAGE: bootAppBuildVM
   Boot your $APPBUILDERVM to construct debain based initrds and linux kernels"
    else
	echo "ERROR:  must specificy buidervm disk image"
	echo "USAGE: bootAppBuildVM <disk image>"
    fi
    exit -1
fi
    
echo "SSH PORT 22 forwarded to $SSHLOCAL. Use this to ssh to VM"

VM_SSH=true VM_CD='' VM_GRAPHICS='' VM_MEMORY=${APPBUILDER_MEMORY:-2048} VM_SSHLOCAL=${APPBUILDER_SSHLOCAL} VM_CPUS=${APPBUILDER_CPUS:-4} $scriptdir/startVM $disk
