#!/bin/bash
#set -x

#DEFAULTS
SSHLOCALFWD=${SSHLOCALFWD:-"127.0.0.1:2223"}
NET="192.168.1.0/24"
NODE=${NODE:-"vm-0-0"}
MAC=${MAC:-"52:54:00:12:34:56"}
IP=${IP:-"192.168.1.5/24"}
RUNDIR=${RUNDIR:-$(pwd)}
MEMSIZE=${MEMSIZE:-8192}

CTLFILE=${CTLFILE:-${NODE}}
CTLFILE=${CTLFILE%%.pipe}.pipe

mknod ${RUNDIR}/${CTLFILE} p

MYUSER=${MYUSER:-$USER}
MYIP=${MYIP:-"192.168.1.2"}

usage="$0 <appdir> [extra command line arguments]
	  eg.  runApp Appliances/apps/genricApp \"appDebug\"
	       runApp Appliances/apps/genricApp \"appEnd='bash'\"
	       runApp Appliances/apps/genricApp \"appEnd='bash' appCmds='ls:mkdir -h:'\"
	  real usage string goes here ;-)"

RUNNER=kvm
# Given that we want control of the ip addresses explicilty to better simulate hardware setups we
# explicitly specify both the host and guest ip addresses
RUNNER_ARGS=${AppRunnerArgs:-"-display none -serial stdio -netdev user,id=network0,net=${NET},host=${MYIP},hostfwd=tcp:${SSHLOCALFWD}-${IP%%/*}:22 -device e1000,netdev=network0,mac=${MAC}"}

appdir=$1
appname=${appdir}
appkernel=${appdir}/vmlinuz
appinitrd=${appdir}/initrd
appcmdline=${appdir}/cmdline

# TRAP on all normal terminations HUP/1, INT/2, QUIT/3, TERM/15, ERR
#trap cleanup 1 2 3 15 EXIT
trap "cleanup $$" EXIT


function killchildren 
{
#  echo "killchildren : $1"
  ppid=$1
  if [[ -z $ppid ]]
  then
    ppid=$$
  fi
  children=$(ps --ppid $ppid -o '%p %a' --no-headings)
  echo "$children" | while read pid args
  do
    if [[ -n $pid ]]
    then
#      echo "killing: $pid : $args"
      kill -9 $pid > /dev/null 2>&1
    fi
  done
}

function cleanup
{
#  echo "cleaning up" > /dev/stderr
  killchildren
}

function USAGE()
{
    echo "$usage" > /dev/stderr
}

if [[ ! -d $appdir ]]; then
    echo "ERROR: bad app directory: $appdir"
    USAGE
    exit -1
fi

if [[ ! -e $appkernel ]]; then
    echo "ERROR: could not locate kernel: $appkernel (don't forget to simlink your kernel)" > /dev/stderr
    ls -l $appdir > /dev/stderr
    USAGE
    exit -1
fi

if [[ ! -e $appinitrd ]]; then
    echo "ERROR: could not locate initrd: $appinitrd (don't forget to simlink your initrd)" > /dev/stderr
    ls -l $appdir > /dev/stderr 
    USAGE
    exit -1
fi

if [[ ! -e $appcmdline ]]; then
    echo "ERROR: could not locate cmdline: $appcmdline (don't forget to simlink your cmdlineargs)" > /dev/stderr
    ls -l $appdir > /dev/stderr 
    USAGE
    exit -1
fi
cmdline="$(cat ${appcmdline})"

shift

echo ${RUNNER} ${RUNNER_ARGS} \
          -m ${MEMSIZE} \
          -kernel ${appkernel}\
	  -initrd ${appinitrd}\
	  -append "appMac='${MAC}' appIp='${IP}' appNode='${NODE}' appCtlServer='${MYIP}' appCtlUser='${MYUSER}' appCtlDir='${RUNDIR}' appCtlFile='${CTLFILE}' ${cmdline} $@"
${RUNNER} ${RUNNER_ARGS} \
	  -m ${MEMSIZE} \
	  -kernel ${appkernel}\
	  -initrd ${appinitrd}\
	  -append "appMac='${MAC}' appIp='${IP}' appNode='${NODE}' appCtlServer='${MYIP}' appCtlUser='${MYUSER}' appCtlDir='${RUNDIR}' appCtlFile='${CTLFILE}' ${cmdline} $@"
