#!/bin/bash
#set -x
NET=${NET:-"192.168.1.0/24"}
NODE=${NODE:-""}
MAC=${MAC:-""}
IP=${IP:-""}
NODEDIR=${NODEDIR:-$(pwd)}

mknod ${NODEDIR}/${NODE}-${IP%%/*}.out p

MYUSER=${MYUSER:-$USER}
MYIP=${MYIP:-"192.168.1.2"}

usage="NODE=<node> IP=<ip/netclass> $0 <appdir> [extra command line arguments]
	  eg.  runApp Appliances/apps/genricApp \"appDebug\"
	       runApp Appliances/apps/genricApp \"appEnd='bash'\"
	       runApp Appliances/apps/genricApp \"appEnd='bash' appCmds='ls:mkdir -h:'\"
	  real usage string goes here ;-)"

appdir=$1
appname=${appdir}
appkernel=${appdir}/vmlinuz
appinitrd=${appdir}/initrd
appcmdline=${appdir}/cmdline

function USAGE()
{
    echo "$usage" > /dev/stderr
}

if [[ ! -d $appdir ]]; then
    echo "ERROR: bad app directory: $appdir"
    USAGE
    exit -1
fi

if [[ ! -e $appkernel ]]; then
    echo "ERROR: could not locate kernel: $appkernel (don't forget to simlink your kernel)" > /dev/stderr
    ls -l $appdir > /dev/stderr
    USAGE
    exit -1
fi

if [[ ! -e $appinitrd ]]; then
    echo "ERROR: could not locate initrd: $appinitrd (don't forget to simlink your initrd)" > /dev/stderr
    ls -l $appdir > /dev/stderr 
    USAGE
    exit -1
fi

if [[ ! -e $appcmdline ]]; then
    echo "ERROR: could not locate cmdline: $appcmdline (don't forget to simlink your cmdlineargs)" > /dev/stderr
    ls -l $appdir > /dev/stderr 
    USAGE
    exit -1
fi
cmdline="$(cat ${appcmdline})"

shift 

# stuff unique to boot nodes via tftp
SSH=ssh
hiluser=${HIL_USER:-handong}
hilhost=${HIL_HOST:-"10.255.0.1"}
hilinfocmd=${HIL_INFO_CMD:-"hil node show"}
hilrebootcmd=${HIL_REBOOT_CMD:-"hil node power cycle"}
hilconsolecmd=${HIL_CONSOLE_CMD:-"hil node console show"}

if [[ -z $NODE ]]; then
    echo "ERROR: must specify node"
    USAGE
    exit -1
fi

if [[ -z $IP ]]; then
    echo "ERROR: must specify ip"
    USAGE
    exit -1
fi

TS=$(date +"%m.%d.%y-%H.%M.%S")
tftproot=/var/lib/tftpboot
tftpGrubCfgDir=${tftproot}/pxelinux.cfg
grubCfgFile=${tftpGrubCfgDir}/${NODE}
tftpKernel=linux/bzImage.${NODE}
tftpInitrd=linux/initrd.${NODE}

# if mac is empty then try and figure it out from tftproot
if [[ -z $MAC ]]; then
    macs=$(${SSH} ${hiluser}@${hilhost} ${hilinfocmd} ${NODE} | echo $(egrep 'Macaddr|Networks') | tr -d ' ')
    macs=${macs//|Macaddr|/}
    macs=${macs//||Networks|/ }
    macs=${macs//|/$'\n'}
    echo "ERROR: Must specify a MAC address for this node's control network connection"
    echo "${macs}"
    exit -1
fi

# install kernel
echo cp ${appkernel} ${tftproot}/${tftpKernel}
if ! cp ${appkernel} ${tftproot}/${tftpKernel}; then
   echo "ERROR: Failed to install ${appkernel} to ${tftproot}/${tftpKernel}" > /dev/stderr
   exit -1
fi
ls -lH ${appkernel} ${tftproot}/${tftpKernel}

# install initrd
echo cp ${appinitrd} ${tftproot}/${tftpInitrd}
if ! cp ${appinitrd} ${tftproot}/${tftpInitrd}; then
   echo "ERROR: Failed to install ${appinitrd} to ${tftproot}/${tftpInitrd}" > /dev/stderr
   exit -1
fi
ls -Hl ${appinitrd} ${tftproot}/${tftpInitrd}

# backup old grub
if [[ -e ${grubCfgFile} ]]; then
   echo  cp ${grubCfgFile} ${grubCfgFile}.${TS}_old
fi

cat > ${grubCfgFile} <<EOF
DEFAULT vesamenu.c32
TIMEOUT 1
ONTIMEOUT linux
PROMPT 0

LABEL linux
      MENU LABEL Linux-5.5.0
      KERNEL ${tftpKernel}
      APPEND initrd=${tftpInitrd}  appMac='${MAC}' appIp='${IP}' appNode='${NODE}' appCtlServer='${MYIP}' appCtlUser='${MYUSER}' appCtlDir='${NODEDIR}' ${cmdline} $@
      ENDTEXT

EOF

cat ${grubCfgFile}

if ! ${SSH} ${hiluser}@${hilhost} ${hilrebootcmd} ${NODE}; then
    echo "ERROR:  Failed to power cycle $NODE" > /dev/stderr
    exit -1
fi

${SSH} ${hiluser}@${hilhost} ${hilconsolecmd} ${NODE}
