#!/bin/bash
#set -x

VMNET="192.168.1.0/24"
VMMAC="52:54:00:12:34:56"
VMIP="192.168.1.5/24"
VMNODE="vm-0-0"
VMNODEDIR=$(pwd)

MYUSER=$USER
MYIP="192.168.1.2"

usage="$0 <appdir> [extra command line arguments]
	  eg.  runApp Appliances/apps/genricApp \"appDebug\"
	       runApp Appliances/apps/genricApp \"appEnd='bash'\"
	       runApp Appliances/apps/genricApp \"appEnd='bash' appCmds='ls:mkdir -h:'\"
	  real usage string goes here ;-)"

RUNNER=kvm
RUNNER_ARGS=${AppRunnerArgs:-"-display none -serial stdio -netdev user,id=network0,net=${VMNET},hostfwd=tcp:127.0.0.1:2223-:22 -device e1000,netdev=network0,mac=${VMMAC}"}

appdir=$1
appname=${appdir}
appkernel=${appdir}/vmlinuz
appinitrd=${appdir}/initrd
appcmdline=${appdir}/cmdline

function USAGE()
{
    echo "$usage" > /dev/stderr
}

if [[ ! -d $appdir ]]; then
    echo "ERROR: bad app directory: $appdir"
    USAGE
    exit -1
fi

if [[ ! -e $appkernel ]]; then
    echo "ERROR: could not locate kernel: $appkernel (don't forget to simlink your kernel)" > /dev/stderr
    ls -l $appdir > /dev/stderr
    USAGE
    exit -1
fi

if [[ ! -e $appinitrd ]]; then
    echo "ERROR: could not locate initrd: $appinitrd (don't forget to simlink your initrd)" > /dev/stderr
    ls -l $appdir > /dev/stderr 
    USAGE
    exit -1
fi

if [[ ! -e $appcmdline ]]; then
    echo "ERROR: could not locate cmdline: $appcmdline (don't forget to simlink your cmdlineargs)" > /dev/stderr
    ls -l $appdir > /dev/stderr 
    USAGE
    exit -1
fi
cmdline="$(cat ${appcmdline})"

shift

echo ${RUNNER} ${RUNNER_ARGS} -kernel ${appkernel}  -initrd ${appinitrd} -append "${cmdline} $@"
${RUNNER} ${RUNNER_ARGS} -kernel ${appkernel}  -initrd ${appinitrd} -append "appMac='${VMMAC}' appIp='${VMIP}' appNode='${VMNODE}' appCtlServer='${MYIP}' appCtlUser='${MYUSER}' appCtlDir='${VMNODEDIR}' ${cmdline} $@"
