#!/bin/bash
APPBUILDER_SSHLOCAL=${APPBUILDER_SSHLOCAL:-"127.0.0.1:2222"}
APPBUILDER_USER=${APPBUILDER_USER:-"sesa"}

if [[ $# == 0 ]]; then
    echo "use localhost: to target buider vm.  Port is taken care of for you"
    echo "You can set APPBUILDER_SSHLOCAL to over ride ip and port.  Eg. SSHLOCAL="127.0.0.1:2223"
    exit -1
fi

port=${APPBUILDER_SSHLOCAL##*:}

set -u

scp -P $port -o "USER=${APPBUILD_USER}" $@
