#!/bin/bash
#set -x
USAGE="$0 <reference root>
     This script updates a reference dir with current 
     reference files from the appbuilder repository"

dir=$(readlink -f  $0)
dir=$(dirname $dir)
filedir=${dir}/../files

if [[ ! -e ${filedir}/init ]]; then
  echo "ERROR: Failed to find appbuilder reference files" >> /dev/stderr
  exit -1
fi

refroot=$1

if [[ -z $refroot ]]; then
   echo "$USAGE"
   exit -1
fi

(cd $filedir; git pull)

sudo cp $filedir/init $refroot
echo Updated init
sudo cp $filedir/chroot $refroot
echo Updated chroot
sudo cp $filedir/initcmds $refroot
echo Updated initcmds 

if [[ ! -d $refroot/app ]]; then
    sudo mkdir -p $refroot/app
    sudo cp -r $filedir/app/* $refroot/app
    echo updated app dir with default files
fi

if sudo bash -c "[[ ! -d $refroot/root/.ssh ]]"; then
    sudo mkdir -p $refroot/root/.ssh && sudo chmod 0700 $refroot/root/.ssh
    sudo cp -r $filedir/ssh/* $refroot/root/.ssh
    echo udpated root/.ssh with defaults
fi

sudo cp $filedir/sshd/sshd_config $refroot/root/etc/ssh/sshd_config
echo Updated /etc/ssh/sshd_config
